# services:
#   report-env:
#     image: kayleeli/dsci310_g6_milestone1
#     ports:
#       - "10000:8888"
#     volumes:
#       - ./reports:/home/jovyan/work/reports
#       - ./data:/home/jovyan/work/data
#       - ./src:/home/jovyan/work/src
#     command: start-notebook.sh --NotebookApp.token=''

services:
  report-env:
    image: nt2103/dsci310_g6
    ports:
      - "10000:8787"
    volumes:
      - ./reports:/home/rstudio/work/reports
      - ./data:/home/rstudio/work/data
      - ./src:/home/rstudio/work/src
    environment: 
      PASSWORD: "password" # Set password to password; Needs GUI
      DISABLE_AUTH: "true"