services:
  report-env:
    image: nt2103/dsci310_g6
    ports:
      - "10000:8787"
    volumes:
      - "./reports:/home/rstudio/work/reports"
      - "./data:/home/rstudio/work/data"
      - "./src:/home/rstudio/work/src"
      - "./output:/home/rstudio/work/output"
      - "./docs:/home/rstudio/work/docs"
      - "./Makefile:/home/rstudio/Makefile"
    environment:
      DISABLE_AUTH: true
    working_dir: /home/rstudio
