name: base
channels:
  - pytorch-nightly
  - conda-forge
  - defaults
dependencies:
  - r-base=4.2.3
  - r-bit=4.0.5
  - r-bit64=4.0.5
  - r-broom=1.0.5
  - r-cli=3.6.2
  - r-conflicted=1.2.0
  - r-crayon=1.5.2
  - r-dials=1.2.0
  - r-dplyr=1.1.4
  - r-ellipsis=0.3.2
  - r-fansi=1.0.6
  - r-generics=0.1.3
  - r-ggplot2=3.4.4
  - r-glmnet=4.1_8
  - r-glue=1.7.0
  - r-hardhat=1.3.0
  - r-janitor=2.2.0
  - r-lattice=0.22_5
  - r-lifecycle=1.0.4
  - r-lubridate=1.9.3
  - r-magrittr=2.0.3
  - r-numderiv=2016.8_1.1
  - r-parsnip=1.2.0
  - r-patchwork=1.1.3
  - r-pillar=1.9.0
  - r-purrr=1.0.2
  - r-recipes=1.0.9
  - r-rlang=1.1.3
  - r-rpart=4.1.23
  - r-rsample=1.2.0
  - r-rstudioapi=0.15.0
  - r-scales=1.3.0
  - r-statmod=1.5.0
  - r-survival=3.5_8
  - r-tibble=3.2.1
  - r-tidymodels=1.1.1
  - r-tidyr=1.3.1
  - r-tidyselect=1.2.1
  - r-tidyverse=2.0.0
  - r-tune=1.1.2
  - r-vcd=1.4_11
  - r-vctrs=0.6.5
  - r-withr=3.0.0
  - r-workflows=1.1.4
  - r-workflowsets=1.0.1
  - r-yardstick=1.3.0
  - r-zeallot=0.1.0
  - python=3.8.18
  - pip=23.3.1