# Environment for DSCI 310 Group 6 project.
# We use `r-base=4.*` instead of a specific version like `r-base=4.2.1`
# because Conda-Forge does not consistently offer all R packages for that version.
# Using a wildcard ensures compatibility with the R 4.x ecosystem.

name: dsci310g6-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - r-base=4.*
  - quarto=1.6.43
  - pip
  - pip:
      - pandas==2.0.3
      - ucimlrepo==0.0.7
  - r-tidyverse
  - r-tidymodels
  - r-glmnet
  - r-rose
  - r-docopt
  - r-devtools
  - r-pointblank

# After creating the environment, run the following command in an R terminal:
# devtools::install_github("DSCI-310-2025/predictdiabetes@1.0.0")
# (Conda does not natively support installing packages directly from GitHub.)
